ip_stack: dual

resolver:
  concurrency: 2

rules:
  test:
    targets:
    - 1.1.1.1
    - 1.1.1.0/24
    - 2.2.2.2
    - 3.3.3.0/24
    - AS1273
    # - https://core.telegram.org/resources/cidr.txt

    exclude:
    - 3.3.3.3/25
    - 3.3.3.255
