ip_stack: dual

owned_networks:
  - 8.8.8.8

resolver:
  concurrency: 2

rules:
  test:
    targets:
      - 1.1.1.0/24
      - 2.2.2.2
      - 3.3.3.0/24
      - test.localhost
      - one.one.one.one
      - dns.google *.dns.google
      - мвд.рф
      # - AS1273 https://core.telegram.org/resources/cidr.txt

    exclude:
    - 3.3.3.3

nftables:
  test.nft:
    sets:
      test:
        rules: [test]
        with_exclude: true

      special:
        rules: [$special]

dnsmasq:
  dnsmasq.conf:
    domains:
      - rules: [test]
        server: 127.0.0.1:53
        nftset: test