#!/usr/bin/env bash
#
# Deploys the tool to the server
#

set -eu
cd "$(dirname "$(realpath "$0")")"

project=routectl
target=x86_64-unknown-linux-gnu

host=root@server.lan
install_path="/usr/local/bin/$project"

rustup target add "$target"

(
    # Assumes installed https://github.com/messense/homebrew-macos-cross-toolchains
    export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc
    cargo build --release --target "$target"
)

scp "target/$target/release/$project" "$host:$install_path"
ssh -t "$host" -- "
    # To not hit service restart limits after multiple reconfigurations
    systemctl --quiet is-active dnsmasq.service && systemctl reset-failed dnsmasq.service

    '$install_path' configure
"